### PR TITLE
Fixed problems with backslash on Windows

### PR DESCRIPTION
**Pull request by tompazourek**
I fixed the problems described in this issue:
https://github.com/stevoland/grunt-es6-module-wrap-default/issues/1

The path will now always have forward slashes, even on Windows machines.

I tested this on my Windows machine in the _react-bootstrap_ project and it seems to be working without any problems now.

### CODE REVIEW

**Comment by stevoland** [comment]
Great, thanks!

**Comment by tompazourek** [comment]
Thanks for the merge. :+1:  Any change I could get it on npm anytime soon?

**Comment by stevoland** [comment]
Sorry for the delay, I've had loads of trouble publishing to npm. It's there now.

**Comment by tompazourek** [comment]
Sure. Thank you very much.

**Pull request merged**
